workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.lamasparsha.merodriver"
        GRADLE_OPTS: "-Xmx3072m"
        JAVA_TOOL_OPTIONS: "-Xmx3072m"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk \
            --release \
            --build-number=$(($(date +%s) / 60))
      - name: Build AAB
        script: |
          flutter build appbundle \
            --release \
            --build-number=$(($(date +%s) / 60))
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        BUNDLE_ID: "com.lamasparsha.merodriver"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        XCODE_PROJECT: "ios/Runner.xcodeproj"
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.lamasparsha.merodriver
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd ios && pod install --repo-update && cd ..
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build IPA for real device
        script: |
          flutter build ipa \
            --release \
            --build-number=$(($(date +%s) / 60)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true

  full-workflow:
    name: Full Build (Android + iOS)
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.lamasparsha.merodriver"
        BUNDLE_ID: "com.lamasparsha.merodriver"
        GRADLE_OPTS: "-Xmx3072m"
        JAVA_TOOL_OPTIONS: "-Xmx3072m"
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.lamasparsha.merodriver
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build Android APK
        script: |
          flutter build apk \
            --release \
            --build-number=$(($(date +%s) / 60))
      - name: Build Android AAB
        script: |
          flutter build appbundle \
            --release \
            --build-number=$(($(date +%s) / 60))
      - name: Install iOS pods
        script: |
          cd ios && pod install --repo-update && cd ..
      - name: Set up iOS code signing
        script: |
          xcode-project use-profiles
      - name: Build IPA for real device
        script: |
          flutter build ipa \
            --release \
            --build-number=$(($(date +%s) / 60)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa/*.ipa
    publishing:
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true